app:
  name: mysql
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
  image: ghcr.io/joeckr/mysql
  tag: latest
  pullPolicy: Always
  port: 3306
  db: mysql
  user: mysql
  password: changeme  # betterleaks:allow
  rootPassword: really_replaceme  # betterleaks:allow
  storageAccessMode: ReadWriteOnce
  storageSize: 1Gi
  storageClass: ""
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
    fsGroup: 1031 # take this out if deploying to OpenShift
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

initSchema:
  enabled: true
